For(
    target=Name(
        value="num",
        lpar=[],
        rpar=[],
    ),
    iter=List(
        elements=[
            Element(
                value=Integer(
                    value="1",
                    lpar=[],
                    rpar=[],
                ),
                comma=Comma(
                    whitespace_before=SimpleWhitespace(
                        value="",
                    ),
                    whitespace_after=SimpleWhitespace(
                        value=" ",
                    ),
                ),
            ),
            Element(
                value=Integer(
                    value="2",
                    lpar=[],
                    rpar=[],
                ),
                comma=Comma(
                    whitespace_before=SimpleWhitespace(
                        value="",
                    ),
                    whitespace_after=SimpleWhitespace(
                        value=" ",
                    ),
                ),
            ),
            Element(
                value=Integer(
                    value="3",
                    lpar=[],
                    rpar=[],
                ),
                comma=MaybeSentinel.DEFAULT,
            ),
        ],
        lbracket=LeftSquareBracket(
            whitespace_after=SimpleWhitespace(
                value="",
            ),
        ),
        rbracket=RightSquareBracket(
            whitespace_before=SimpleWhitespace(
                value="",
            ),
        ),
        lpar=[],
        rpar=[],
    ),
    body=IndentedBlock(
        body=[
            SimpleStatementLine(
                body=[
                    Expr(
                        value=Call(
                            func=Name(
                                value="print",
                                lpar=[],
                                rpar=[],
                            ),
                            args=[
                                Arg(
                                    value=Name(
                                        value="num",
                                        lpar=[],
                                        rpar=[],
                                    ),
                                    keyword=None,
                                    equal=MaybeSentinel.DEFAULT,
                                    comma=MaybeSentinel.DEFAULT,
                                    star="",
                                    whitespace_after_star=SimpleWhitespace(
                                        value="",
                                    ),
                                    whitespace_after_arg=SimpleWhitespace(
                                        value="",
                                    ),
                                ),
                            ],
                            lpar=[],
                            rpar=[],
                            whitespace_after_func=SimpleWhitespace(
                                value="",
                            ),
                            whitespace_before_args=SimpleWhitespace(
                                value="",
                            ),
                        ),
                        semicolon=MaybeSentinel.DEFAULT,
                    ),
                ],
                leading_lines=[],
                trailing_whitespace=TrailingWhitespace(
                    whitespace=SimpleWhitespace(
                        value="",
                    ),
                    comment=None,
                    newline=Newline(
                        value=None,
                    ),
                ),
            ),
        ],
        header=TrailingWhitespace(
            whitespace=SimpleWhitespace(
                value="",
            ),
            comment=None,
            newline=Newline(
                value=None,
            ),
        ),
        indent=None,
        footer=[],
    ),
    orelse=None,
    asynchronous=None,
    leading_lines=[],
    whitespace_after_for=SimpleWhitespace(
        value=" ",
    ),
    whitespace_before_in=SimpleWhitespace(
        value=" ",
    ),
    whitespace_after_in=SimpleWhitespace(
        value=" ",
    ),
    whitespace_before_colon=SimpleWhitespace(
        value="",
    ),
)
